import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowUpRight, ArrowRight, ShieldCheck, Users, Globe2, Check, Building2, Hotel, Factory, Hospital, Warehouse, HardHat, BriefcaseBusiness } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { CallToAction } from '@/components/site';
import { ServiceCard } from '@/components/service-card';
import { services, pageHead } from '@/lib/business';
import hero from '@/assets/workforce-hero.jpg';
import team from '@/assets/hospitality.jpg';
export const Route=createFileRoute('/')({head:()=>pageHead('Workforce solutions. Human possibilities.','Manpower, security, housekeeping and hospitality staffing for businesses in India and UAE. Connect with Yaabesh Grace in Jaipur.'),component:Home});
function Home(){return <><section className="hero"><img className="hero-image" src={hero} width={1920} height={1024} fetchPriority="high" alt="Indian manpower, security, housekeeping and hospitality professionals"/><div className="hero-shade"/><div className="wrap hero-content"><span className="hero-eyebrow"><span/>YOUR GLOBAL PARTNER IN PEOPLE & SERVICES</span><h1>Yaabesh Grace<span>Good people.<br/><em>Greater possibilities.</em></span></h1><p>From skilled manpower to exceptional hospitality,<br className="desktop-break"/> we bring the right people to your business.</p><div className="hero-actions"><Button asChild variant="gold" size="lg"><Link to="/services">Discover our services <ArrowUpRight/></Link></Button><Button asChild variant="heroOutline" size="lg"><Link to="/careers">Find your opportunity <ArrowRight/></Link></Button></div><div className="hero-footnote"><Globe2 size={17}/><span>Connecting people & businesses across <strong>India and UAE</strong></span></div></div><div className="hero-side-label">PEOPLE FIRST. ALWAYS.</div></section><section className="promise-strip"><div className="wrap promise-grid">{[{icon:Users,title:'People-focused approach',text:'Your requirements. The right fit.'},{icon:ShieldCheck,title:'Dependable workforce',text:'Support for your daily operations.'},{icon:Globe2,title:'India & UAE connections',text:'Local understanding. Wider possibilities.'}].map(({icon:Icon,title,text})=><div key={title}><Icon/><span><strong>{title}</strong><small>{text}</small></span></div>)}</div></section>
<section className="section wrap"><div className="section-heading"><div><span className="eyebrow">WHAT WE DO</span><h2>People for every purpose.</h2><p>One partner. A world of workforce solutions.</p></div><Button asChild variant="outline"><Link to="/services">View all services <ArrowUpRight/></Link></Button></div><div className="services-grid">{services.slice(0,3).map((s,i)=><ServiceCard key={s.slug} service={s} index={i}/>)}</div><div className="more-services"><span>And that's not all.</span><Link to="/services">Hospitality & hotels <ArrowUpRight size={14}/></Link><Link to="/services">Food & catering <ArrowUpRight size={14}/></Link><Link to="/services">Civil workforce <ArrowUpRight size={14}/></Link></div></section>
<section className="about-band"><div className="wrap about-layout"><div className="about-image"><img src={team} width={1024} height={768} loading="lazy" alt="Hospitality professionals welcoming guests"/><div className="image-caption"><Globe2/><span>Rooted in India.<strong>Connected to opportunity.</strong></span></div></div><div className="about-copy"><span className="eyebrow">MORE THAN MANPOWER</span><h2>Behind every great business,<br/>there are great people.</h2><p>At Yaabesh Grace Workforce International Pvt. Ltd., we connect business needs with human potential. From the first conversation to finding the right team, people stay at the heart of what we do.</p><p>Based in Jaipur, we bring together workforce solutions across manpower, security, housekeeping and hospitality, with a focus on India and the UAE.</p><div className="check-list"><span><Check/>Workforce tailored to your requirements</span><span><Check/>A dedicated point of contact</span><span><Check/>Opportunities across multiple industries</span></div><Button asChild variant="default"><Link to="/about">Meet Yaabesh Grace <ArrowUpRight/></Link></Button></div></div></section>
<section className="section wrap industries"><div className="section-heading"><div><span className="eyebrow">WHERE WE MAKE A DIFFERENCE</span><h2>Different industries. One commitment.</h2></div><p>From the hotel lobby to the construction site,<br/>we help businesses build their teams.</p></div><div className="industry-grid">{[{icon:Hotel,title:'Hotels & hospitality'},{icon:Building2,title:'Corporate offices'},{icon:Factory,title:'Industrial facilities'},{icon:HardHat,title:'Construction & civil'},{icon:Hospital,title:'Healthcare facilities'},{icon:Warehouse,title:'Warehousing & logistics'}].map(({icon:Icon,title})=><Link to="/services" key={title}><Icon/><span>{title}</span><ArrowUpRight className="industry-arrow" size={16}/></Link>)}</div></section>
<section className="process-band"><div className="wrap section"><span className="eyebrow">A SIMPLE PATH TO THE RIGHT TEAM</span><h2>From your requirement<br/>to your workforce.</h2><div className="process-grid">{[{title:'Tell us what you need',text:'Share your industry, location, roles and team size.'},{title:'Find the right fit',text:'We discuss suitable profiles and your staffing requirements.'},{title:'Bring your team together',text:'Agree on the scope and coordinate the next steps.'},{title:'Keep moving forward',text:'Stay connected with our team as your needs evolve.'}].map((s,i)=><div key={s.title}><span className="step-number">0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p></div>)}</div><Link to="/contact" className="text-link">Start a conversation <ArrowUpRight size={18}/></Link></div></section>
<section className="section wrap opportunity-section"><div><span className="eyebrow">YOUR SKILLS. YOUR NEXT CHAPTER.</span><h2>Looking for work?<br/>Let's find your way forward.</h2><p>Explore roles in housekeeping, security, hospitality, civil work and more. Share your experience and preferred location with our team.</p><div className="role-tags"><span>India</span><span>UAE</span><span>Skilled & support roles</span></div><Button asChild variant="default"><Link to="/careers">Explore opportunities <ArrowUpRight/></Link></Button></div><div className="opportunity-list">{['Hotel & front office','Cooks, waiters & catering','Security & housekeeping','Civil & industrial workforce'].map((r,i)=><Link to="/careers" key={r}><span className="role-index">0{i+1}</span><span>{r}</span><ArrowUpRight size={20}/></Link>)}<small><BriefcaseBusiness size={15}/> Roles are subject to current employer requirements.</small></div></section><CallToAction/></>}
