import { Link } from '@tanstack/react-router';
import { useState, type FormEvent } from 'react';
import { ArrowUpRight, Phone, Mail, MapPin, Menu, X, MessageCircle, Send, BriefcaseBusiness, Globe2, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import logo from '@/assets/yaabesh-logo.png.asset.json';
import { business, services, whatsappLink } from '@/lib/business';

export function Brand() { return <Link to="/" className="brand"><img src={logo.url} width={197} height={161} alt="Yaabesh Grace original YG logo" /><span><strong>YAABESH <em>GRACE</em></strong><small>WORKFORCE INTERNATIONAL PVT. LTD.</small></span></Link>; }
export function Header() { const [open,setOpen]=useState(false); return <><div className="topbar"><div className="wrap topbar-inner"><span>People <i>•</i> Progress <i>•</i> Global Success</span><div><a href={`mailto:${business.email}`}><Mail size={13}/>{business.email}</a><a href={`tel:${business.whatsapp}`}><Phone size={13}/>{business.phone}</a></div></div></div><header className="header"><div className="wrap header-inner"><Brand/><nav className={open?'nav is-open':'nav'} aria-label="Main navigation">{([{to:'/',label:'Home'},{to:'/about',label:'About us'},{to:'/services',label:'Our services'},{to:'/careers',label:'Find a job'},{to:'/contact',label:'Contact'}] as const).map(item=><Link key={item.to} to={item.to} activeOptions={{exact:true}} activeProps={{className:'active'}} onClick={()=>setOpen(false)}>{item.label}</Link>)}</nav><Button asChild variant="gold" className="header-cta"><Link to="/contact">Hire your team <ArrowUpRight/></Link></Button><Button variant="ghost" size="icon" className="menu-toggle" aria-label={open?'Close navigation':'Open navigation'} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div></header></>; }
export function Footer() { return <footer className="footer"><div className="wrap footer-grid"><div><Brand/><p>Your global partner in people & services.<br/>Connecting businesses with the people who move them forward.</p><span className="country-label"><Globe2 size={16}/> India & UAE</span></div><div><h3>Explore</h3><Link to="/about">About us</Link><Link to="/services">Our services</Link><Link to="/careers">Find a job</Link><Link to="/faq">FAQs</Link></div><div><h3>Our expertise</h3>{services.slice(0,4).map(s=><Link key={s.slug} to="/services">{s.title}</Link>)}</div><div><h3>Let's connect</h3><a href={`tel:${business.whatsapp}`}><Phone size={15}/>{business.phone}</a><a href={`mailto:${business.email}`}><Mail size={15}/>{business.email}</a><p className="address"><MapPin size={17}/>{business.address}</p></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Yaabesh Grace Workforce International Pvt. Ltd.</span><div><Link to="/terms">Terms & conditions</Link><Link to="/privacy">Privacy policy</Link></div></div></footer>; }
export function EnquiryForm({initialMode='service'}:{initialMode?:'service'|'job'}) { const [mode,setMode]=useState(initialMode); const [ready,setReady]=useState<string>(); function submit(e:FormEvent<HTMLFormElement>) { e.preventDefault(); const data=new FormData(e.currentTarget); const message=`${mode==='job'?'Job application':'Service enquiry'} — Yaabesh Grace\nName: ${data.get('name')}\nPhone: ${data.get('phone')}\n${mode==='job'?'Role':'Service'}: ${data.get('category')}\nLocation: ${data.get('location')}\nDetails: ${data.get('message') || 'Please contact me.'}`; const url=whatsappLink(message); setReady(url); window.open(url,'_blank','noopener,noreferrer'); } return <div className="enquiry-form"><div className="mode-tabs"><Button variant={mode==='service'?'default':'ghost'} onClick={()=>{setMode('service');setReady(undefined);}}>Hire a team</Button><Button variant={mode==='job'?'default':'ghost'} onClick={()=>{setMode('job');setReady(undefined);}}>Find a job</Button></div><form onSubmit={submit}><div className="form-grid"><label>Full name<input name="name" placeholder="Your name" required autoComplete="name"/></label><label>Phone number<input name="phone" type="tel" placeholder="Your mobile number" required pattern="[+0-9 ()-]{7,20}" autoComplete="tel"/></label></div><label>{mode==='job'?'Area of work':'Service required'}<select name="category" required defaultValue=""><option value="" disabled>Select a category</option>{services.map(s=><option key={s.slug}>{s.title}</option>)}</select></label><label>Preferred location<select name="location" defaultValue="India"><option>India</option><option>UAE</option></select></label><label>{mode==='job'?'Experience & preferred role':'Tell us about your requirement'}<textarea name="message" rows={3} placeholder={mode==='job'?'Your experience, skills and preferred role':'Team size, city and any specific requirements'}/></label><p className="form-note">By continuing, you agree to our <Link to="/privacy">privacy policy</Link>. Your details are shared with our team through WhatsApp.</p><Button variant="gold" type="submit" className="submit-button">Continue on WhatsApp <Send/></Button>{ready&&<a className="form-success" href={ready} target="_blank" rel="noreferrer">Your message is ready. Open WhatsApp to send it <ArrowUpRight size={15}/></a>}</form></div>; }
export function FloatingContact() { const [open,setOpen]=useState(false); const [chat,setChat]=useState(false); return <><div className="floating-contact">{chat&&<div className="whatsapp-card"><strong>Let's talk about your next step.</strong><span>Yaabesh Grace • {business.phone}</span><a href={whatsappLink('Hello Yaabesh Grace, I would like to discuss my requirements.')} target="_blank" rel="noreferrer">Start a conversation <ChevronRight size={16}/></a></div>}<Button variant="default" className="floating-enquiry" title="Send an enquiry" onClick={()=>setOpen(true)}><Send size={18}/><span>Enquire now</span></Button><Button variant="whatsapp" className="floating-whatsapp" title={`WhatsApp ${business.phone}`} aria-label="Open WhatsApp contact" onClick={()=>setChat(!chat)}><MessageCircle/></Button></div>{open&&<div className="modal-backdrop" onClick={()=>setOpen(false)}><section role="dialog" aria-modal="true" aria-labelledby="enquiry-title" className="enquiry-modal" onClick={e=>e.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">LET'S CONNECT</span><h2 id="enquiry-title">How can we help?</h2></div><Button size="icon" variant="ghost" aria-label="Close enquiry" onClick={()=>setOpen(false)}><X/></Button></div><EnquiryForm/></section></div>}</>; }
export function CallToAction() { return <section className="cta-band"><div className="wrap cta-inner"><div><span className="eyebrow">GOOD PEOPLE. GREAT POSSIBILITIES.</span><h2>Your next great team starts here.</h2><p>Tell us what you need. Let's find the right people together.</p></div><Button asChild variant="gold" size="lg"><Link to="/contact">Let's talk <ArrowUpRight/></Link></Button></div></section>; }
export function PageIntro({label,title,description}:{label:string,title:string,description:string}) { return <section className="page-intro"><div className="wrap"><span className="eyebrow">{label}</span><h1>{title}</h1><p>{description}</p><div className="breadcrumbs"><Link to="/">Home</Link><ChevronRight size={14}/><span>{label}</span></div></div></section>; }
